[package]
name = "touche-driver"
version = "0.1.1"
edition = "2024"

[dependencies]
futures-lite = "2.6.0"
mio = "1.0.3"
nusb = "0.1.13"
udev = { version = "0.9.3", features=["mio10"]}
evdev = "0.13.0"
