[package]
name = "touche-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "2.5.0"
mio = "1.0.3"
nusb = "0.1.12"
udev = { version = "0.9.1", features=["mio10"]}
evdev = "0.12.2"
