name: Release builds

on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.release_for }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
        - release_for: Linux x86_64
          os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          name: touche-driver-linux

    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libudev-dev libevdev-dev

      - name: Build executable
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Rename executable
        run: |
          cd ./target/${{ matrix.target }}/release
          mv touche-driver ${{ matrix.name }}

      - name: Upload binary to release
        shell: bash
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
          ./target/${{ matrix.target }}/release/${{ matrix.name }}
